version: '3'

services:
  app:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
    container_name: proxy
    ports:
      - "8080:8080"
    networks:
        - mylocal
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
        - "5432:5432"
    networks:
        - mylocal
networks:
    mylocal:
        driver: bridge
        name: mylocal
